### ISSUE TITLE
how to disable sign up's and limit which users are allowed to sign in?

### ISSUE THREAD

**Issue by maskedband1t** [amaurymartiny/react-redux-auth0-kit#1]

**Comment by maskedband1t** [comment]
Like how do I customize lock options, because the way auth0 shows does not work with this

**Comment by maskedband1t** [comment]
and limit sign up to certain domains?

**Comment by amaury1093** [comment]
All these are done on the Auth0 side, https://manage.auth0.com/.
For instance,
- Disable sign-up: in _Connections_->_Database_ on the left panel, there's a "Disable Sign-ups" option.
-  Limit sign-up domains: in _Connections_->_Enterprise_, create a AD or SAML or any other enterprise connection and put all the allowed email domains.

I'm closing since this is related to Auth0 itself, not this boilerplate.
