### ISSUE TITLE
Local Storage? checkLogin Action?

### ISSUE THREAD

**Issue by kevinswarner** [amaurymartiny/react-redux-auth0-kit#3]
Hi, I am working to implement my react-redux-auth0 solution based on your example. I have a couple questions that you might be able to help me with...

1. Why are you storing the id_token and profile in local storage? Should these not just be stored in the redux store?

2. Why have the checkLogin action? Is there a reason you put the "authenticated" and "authorization_error" event handlers here? I placed mine in the constructor of the AuthService (like the examples provided by Auth0). I am just trying to understand your approach.

Thanks!

**Comment by squarism** [comment]
First, thanks for sharing this example @amaurymartiny.

Funny, @kevinswarner I was just wondering the same thing.  I guess it's acting as a cache of sorts although if you were going to check for expiration then you'd want to change this strategy a bit?  I'm probably not experienced enough yet to modify this, just playing around with this example.  Also, I guess you could use the ES6 spread operator here instead of `Object.assign`.

```
  switch (action.type) {
    case LOCK_SUCCESS:
      return Object.assign({}, state, {
        isFetching: false,
        isAuthenticated: true,
        errorMessage: ''
      })
```
With ES6:
```
  switch (action.type) {
    case LOCK_SUCCESS:
      return { ...state, isFetching: false, isAuthenticated: true, errorMessage: '' }
```

This repo works, it functions.  I tried it against my auth0 config.  I just don't understand this localstate bit and knowing when a user is authenticated.  I'm trying to combine the auth0 example and this repo together.

**Comment by amaury1093** [comment]
Hi @kevinswarner!

1. It's to make sure that the user stays logged in when he refreshes the page. Id_token and profile are in the redux store, but also in the localStorage so that they persist over a short period of time (page refresh, or user comes back after a couple of minutes...). I thought of using `redux-persist` but I wanted to keep in minimal.

2. I get your method, it would perfectly work. My approach was that I was putting everything that's related to the store (i.e. everything that contains a `dispatch`) in the actions folder. The Auth0 blog method would have me have the `dispatch` keyword inside utils/AuthService.js and not in actions, and I didn't like this approach.
My current approach is not perfect. A much clearer way would be to put all these side-effects (basically checkLogin + everything in AuthService.js) inside a saga and delete the utils folder. It would be more into the redux way of doing stuff, but it adds redux-saga.

Hope it makes sense.

**Comment by squarism** [comment]
[Here's an example of a similar project](https://github.com/jch254/starter-pack) to this repo using redux-saga.  Just starting with this, don't grok it yet.

**Comment by kevinswarner** [comment]
Thanks. That makes sense. I was not thinking about page refreshes. Thanks for sharing this repo!
